
// generated by ai
export const timeAgo = (date: string) => {
    const currentTime = new Date();
    const previousTimestamp = new Date(date);
    const timeDifference = Math.floor((currentTime.getTime() - previousTimestamp.getTime()) / 1000);

    if (timeDifference < 60) {
      return '방금 전'
    } else if (timeDifference < 3600) {
      const minutes = Math.floor(timeDifference / 60);
      return `${minutes}분 전`;
    } else if (timeDifference < 86400) {
      const hours = Math.floor(timeDifference / 3600);
      return `${hours}시간 전`;
    } else {
        return `${previousTimestamp.getFullYear()}.${previousTimestamp.getMonth() + 1}.${previousTimestamp.getDay()}`
    }
}